name: RankupSystem
version: '${project.version}'
main: org.rankup.rankupsystem.RankupSystem
commands:
  ranks:
    description: a rank command
  rankup:
    description: To rankup
depend:
  - Vault
softdepend:
  - PlaceholderAPI
